apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .clusterId }}"
  namespace: "{{ .clusterId  }}"
  labels:
    hyperfleet.io/cluster-id: "{{ .clusterId }}"
    hyperfleet.io/resource-type: "service-account"
  annotations:
    hyperfleet.io/generation: "{{ .generation }}"
