apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: status-reporter
  namespace: "{{ .clusterId }}"
  labels:
    hyperfleet.io/cluster-id: "{{ .clusterId }}"
    hyperfleet.io/resource-type: "role-binding"
  annotations:
    hyperfleet.io/generation: "{{ .generationSpec }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: status-reporter
subjects:
  - kind: ServiceAccount
    name: "{{ .clusterId  }}"
    namespace: "{{ .clusterId  }}"
